### PR TITLE
chore: CSS Gallery

### PR DESCRIPTION
**Pull request by Parul1606**
## Related Issue
Closes: #282 

## Description of Changes
I have added a new section to the resources gallery "CSS" and in that, I have added the books section, resources section, and gaming adventures section.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| (
image) | (image) |

image

image

image

image

### CODE REVIEW

**Comment by Parul1606** [comment]
I need help @Alkaison, I have added all the work yet I'm unable to see the resources on the local host. Please help me to clear this problem.

**Comment by Parul1606** [comment]
Please review it as soon as possible @Alkaison

**Comment by Parul1606** [comment]
Please review this PR @Alkaison

**Comment by Alkaison** [comment]
Hi @Parul1606 please resolve the merge conflicts.

**Comment by Parul1606** [comment]
> Hi @Parul1606 please resolve the merge conflicts.

Done

**Review by Alkaison — APPROVED** [review]
All good! wait for @Astrodevil to merge it.

**Pull request merged**
