### PR TITLE
fix: Modifications in frameworks.astro , webdev.astro, javascript.astro Files

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Related Issue

Closes: #240 #241 #239 

## Description of Changes
- **`Replaced Resource Gallery - Frameworks instead of  changed Resource Gallery - Frameworks/Libraries/Tools` in this https://resourcegallery.live/frameworks/   Link**
- **Added `The Odin Project` Details in `src/pages/webdev.astro` File** 
- **Added `Cisco Networking Academy` Details in `src/pages/javascript.astro` File**

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @Alkaison . In this PR, Why Previous 2 PR Changes merged into this PR. Please tell Me Why It's happen?

**Review by Alkaison — CHANGES_REQUESTED** [review]
Please create separate branches for a new PR because it can cause merge conflicts and website won't deploy properly. Please fix them to get merged.

**Comment by NarendraKoya999** [comment]
> Please create separate branches for a new PR because it can cause merge conflicts and website won't deploy properly. Please fix them to get merged.

I have created Separate branches with each PR. But, why should this happens?. Can you please provide step by step Methods?

**Comment by Alkaison** [comment]
> I have created Separate branches with each PR. But, why should this happens?. Can you please provide step by step Methods?

- This might happen because you created the new branch from the last updated branch instead of main branch which cause the commits to appear in new branch too.

- If we merge your 1st PR the 2nd PR will have conflicts and if we merge your 2nd PR after fixing conflicts the 3rd PR will get conflicts.

- Solution: we can close your 1st and 2nd PR and go with your 3rd PR commiting all the 3 changes in one PR and will link your 3 issues with that PR, let me know if you agree with that.

**Comment by NarendraKoya999** [comment]
> > I have created Separate branches with each PR. But, why should this happens?. Can you please provide step by step Methods?
> 
> * This might happen because you created the new branch from the last updated branch instead of main branch which cause the commits to appear in new branch too.
> * If we merge your 1st PR the 2nd PR will have conflicts and if we merge your 2nd PR after fixing conflicts the 3rd PR will get conflicts.
> * Solution: we can close your 1st and 2nd PR and go with your 3rd PR commiting all the 3 changes in one PR and will link your 3 issues with that PR, let me know if you agree with that.

Yes I agree with you. Please Close that  1st and 2nd PR's

**Pull request merged**
