### PR TITLE
Add CSS documentation

### PR DESCRIPTION
**Pull request by Sriparno08**
## Related Issue

Closes: #123

## Description of Changes

I have added a new resource (CSS documentation) to the website.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Screenshot 2023-07-24 104434 | Screenshot 2023-07-24 104418 |

This PR is part of GSSoC'23.

### CODE REVIEW

**Comment by Astrodevil** [comment]
Add css to main resource page and under that add mdn docs resource

**Review by Alkaison — CHANGES_REQUESTED** [review]
Branch has merge conflicts please fix them.

**Comment by Sriparno08** [comment]
Fixed, @Alkaison!

**Comment by Alkaison** [comment]
Can you share a video of the updates live on website?

**Comment by Sriparno08** [comment]
Here you go, @Alkaison.

[Screen Recording.webm](https://github.com/ZeroOctave/resource-gallery/assets/89148144/75599eab-d967-476a-91c5-d8e80b27411c)

**Comment by Sriparno08** [comment]
Hey @Alkaison, I have shared a video. Can you please have a look?

**Comment by Sriparno08** [comment]
Hey @Astrodevil & @Alkaison, can you please have a look at this PR?

**Pull request closed without merging**
