### PR TITLE
Added hovers to the cards

### PR DESCRIPTION
**Pull request by akanksha984**
## Related Issue
https://github.com/ZeroOctave/resource-gallery/issues/226

Closes: #226 

## Description of Changes
I have added hover to the cards
image

## Checklist:

- [ x] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [ x] I have included comments in areas that may be difficult to understand.
- [ x] I have made corresponding updates to the project documentation.
- [ x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by akanksha984** [comment]
@Alkaison please check this

**Comment by Alkaison** [comment]
- Hi @akanksha984, when you hover over a card, the icon/small logo has background of black and color as white in normal mode.
- But when you added dark colors, the icons seem to look small. 
- Can you also invert colors for icon? make the icon background white and icon color as black when hovered. 
-  Let me know if it's possible.

**Comment by akanksha984** [comment]
yes @Alkaison

**Comment by akanksha984** [comment]
image

now ok @Alkaison ??

**Comment by Alkaison** [comment]
Yes perfect, also I noticed you added a scale property when hovered over them, please remove them and push the changes.

**Comment by akanksha984** [comment]
@Alkaison updated

**Review by Alkaison — APPROVED** [review]
Perfect! 👍

**Comment by akanksha984** [comment]
@Alkaison thank you

> Perfect! 👍

**Pull request merged**
