### PR TITLE
added resources

### PR DESCRIPTION
**Pull request by Shreya111111**
## Related Issue

Closes: #168 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
Added the three resources on next js in web development section. kindly review it.
Screenshot 2023-06-24 170746

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Shreya111111** [comment]
@Astrodevil  and @bhartik021  added three resources in web development shown in the screenshot above under issue #168 and PR #170 under gssoc'23. plz revieww it.

**Comment by Shreya111111** [comment]
@Astrodevil added three resources in web development shown in the screenshot above under issue https://github.com/ZeroOctave/resource-gallery/issues/168 and PR https://github.com/ZeroOctave/resource-gallery/pull/170 under gssoc'23. plz revieww it.

**Comment by Shreya111111** [comment]
@Astrodevil  Plz check . It is already many days since PR

**Comment by Shreya111111** [comment]
@Alkaison  plz review the issue https://github.com/ZeroOctave/resource-gallery/issues/168 and PR https://github.com/ZeroOctave/resource-gallery/pull/170 under gssoc'23.

**Review by Alkaison — APPROVED** [review]
The code is perfect to get merged but make sure whenever you open a PR give proper description while submitting the screenshots so that reviewers can understand, what this PR is for.

**Review by Alkaison — APPROVED** [review]
The code is perfect to get merged but make sure whenever you open a PR give proper description while submitting the screenshots so that reviewers can understand, what this PR is for.

**Comment by Shreya111111** [comment]
ok @Alkaison I will take care of that now onwards.

**Comment by Shreya111111** [comment]
@Astrodevil Pls merge the PR

**Comment by Shreya111111** [comment]
@Astrodevil  added three resources in web dev session please merge the PR

**Comment by Shreya111111** [comment]
@Astrodevil  it has been too long and almost more than a week now. kindly review the PR

**Comment by Shreya111111** [comment]
@Astrodevil  I have updated the info and screenshots provided

**Comment by Shreya111111** [comment]
@Astrodevil  kindly review it

**Comment by Shreya111111** [comment]
@Astrodevil it has been too long and almost more than 2 week now. kindly review the PR

**Comment by Alkaison** [comment]
Hi @Shreya111111, we don't know what happened to him, he is not reviewing anyone's PR.

**Comment by Shreya111111** [comment]
@Alkaison why is this so but

**Comment by Shreya111111** [comment]
@Alkaison you are the project review right

**Comment by Alkaison** [comment]
Yes, I review the PR's but I don't have write permission to this repository so I can't merge the PR's.

**Pull request merged**
