### PR TITLE
Added NodeJs and MongoDB Resources

### PR DESCRIPTION
**Pull request by siddarthdayala**
## Related Issue

Closes: #190 

## Description of Changes

- Added NodeJs and MongoDB resources
- Modified only webdev.astro file

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |

image
 image

Please provide any necessary screenshots to illustrate the changes made.

image

### CODE REVIEW

**Review by Alkaison — APPROVED** [review]
Code and resource are good to get merged.

**Comment by siddarthdayala** [comment]
Hey @Alkaison, It seems there are no conflicts in the code. If there are any errors, please update me.

**Comment by Alkaison** [comment]
Hi @siddarthdayala, the code is perfect. You will have to wait for @Astrodevil to merge it because only he has Write access to this repository.

**Comment by Astrodevil** [comment]
@siddarthdayala solve conflict

**Comment by siddarthdayala** [comment]
@Astrodevil resolved the conflict. Please check it

**Review by Alkaison — APPROVED** [review]
Looks good 👍, can you please try to add more resources related to the same domains?

**Comment by siddarthdayala** [comment]
hey @Alkaison will surely add other resources in another PR. Please review this one

**Pull request merged**
