### PR TITLE
feat: Cisco Networking Academy

### PR DESCRIPTION
**Pull request by NarendraKoya999**
…tion

## Related Issue

Closes: #240 

## Description of Changes
- **Added Cisco Networking Academy Details in javascript.astro File in pages Folder**
- **This website is used for Learning Plain JavaScript from Very Beginner's Level to PRO Level.**
- **Also, This website provided Certification gives More Weightage to Personal Portfolio**
- **This website  is provided Free course for Learning JavaScript**

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @Alkaison . Please Review on PR?

**Review by Alkaison — APPROVED** [review]
All good!

**Comment by Alkaison** [comment]
Hi @NarendraKoya999, try adding more resources for the JavaScript domain.

**Comment by NarendraKoya999** [comment]
> Hi @NarendraKoya999, try adding more resources for the JavaScript domain.

Sure. I am happy to contribute with More Worthable Resources of JavaScript

**Comment by Astrodevil** [comment]
@NarendraKoya999  the link is indicating to site where multiple courses are listed, it's not specific to just javascript.

@Alkaison  what do you think? can we make a new resource section for site like these to access multiple course offering free and valuble platforms.

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 the link is indicating to site where multiple courses are listed, it's not specific to just javascript.
> 
> @Alkaison what do you think? can we make a new resource section for site like these to access multiple course offering free and valuble platforms.
** I think Your Suggestion is good for Maintaining the Resources more Comfortable Whatever websites provide Multiple Courses. But,  `Already that type of Websites positioned in Our resources gallery . For Example : MDN Docs`**. Final Choice is yours ??

**Comment by NarendraKoya999** [comment]
> > @NarendraKoya999 the link is indicating to site where multiple courses are listed, it's not specific to just javascript.
> > @Alkaison what do you think? can we make a new resource section for site like these to access multiple course offering free and valuble platforms.
> > @Alkaison  I think Your Suggestion is good for Maintaining the Resources more Comfortable Whatever websites provide Multiple Courses. But, **`Already that type of Websites positioned in Our resources gallery . For Example : MDN Docs. This Website provides not specific to Only JavaScript . But, this is listed in JavaScript Resource Gallery `**. So, Final Choice is yours ??

- **In my Thought Process, I want to  raise one Issue Called "`Top Resources`" at the starting of `Open Source Card.` That means, we can allow only websites like Which Website  provides Multiple options not Stick to only One particular Resource? and add** 
- **`Add star Icon on specific Top Resources Card. It gives more attention to Visited Users.`**
- **If you give me a Chance , I have create a Issue and along with PR !!**

**Comment by NarendraKoya999** [comment]
> * Hi @NarendraKoya999, its great idea to build a `Top Resources` section. Please go for it and do provide details description in their respective issue/PR.
> * For that star resouces idea will see later.
> 
> * @Astrodevil for that section for offering multiple resources websites, how can we implement it? Because our `/resouces` page has section divided according to topics. Can we create a new page for that? or what you think?
> 
> * changes of this PR will be merged under [fix: Modifications in frameworks.astro , webdev.astro, javascript.astro Files #250](https://github.com/ZeroOctave/resource-gallery/pull/250), so close this PR without merging.

**Comment by NarendraKoya999** [comment]
@Alkaison .Thank you for accepted my Request for making New Idea adding to Our Website . I will work on it as soon as Possible

**Pull request closed without merging**
