### PR TITLE
added the dark mode button

### PR DESCRIPTION
**Pull request by parasss19**
Closes: #8

## Description of Changes
- Added the dark mode button with toggle effect

## Checklist:

- [ x] My code adheres to the established style guidelines of this project.
- [x ] I have conducted a self-review of my code.
- [ x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x ] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by parasss19** [comment]
> Solve conflicts and give screenshot of dark mode

Hi @Astrodevil I resolved the conflit and also apply the z index  in navbar so the ninja image does not overlap it 

https://github.com/ZeroOctave/resource-gallery/assets/101205226/0fe7af50-fa4f-4382-9594-36cc97870c9b

**Comment by parasss19** [comment]
> Dark mode is not properly applied, its making the experience bad, need big Improvements across pages as you can see in ss. image

What I have to change?

**Comment by Astrodevil** [comment]
See for yourself in the dark mode screenshots, does it look good? Navbar icons are not visible properly. It looks weird.

Use google and find better dark mode implementation for Astro based sites, Our uses tailwind too.
Take time, solve it!

**Comment by Alkaison** [comment]
- Are you working on this feature?

**Pull request closed without merging**
