### PR TITLE
Added underline hover effect on navbar elements

### PR DESCRIPTION
**Pull request by HimanshuNarware**
Closes: #[#232]

## Description of Changes
Added underline hover effect on the navbar elements.
## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot

) | Updated screenshot

) |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Alkaison** [comment]
Hi @HimanshuNarware, the changes are very minor to be considered for GSSoC program. Can you please to redesign the "Quick Links" section from the navbar.

**Comment by HimanshuNarware** [comment]
> Hi @HimanshuNarware, the changes are very minor to be considered for GSSoC program. Can you please to redesign the "Quick Links" section from the navbar.

Why not

**Comment by HimanshuNarware** [comment]
> Hi @HimanshuNarware, the changes are very minor to be considered for GSSoC program. Can you please to redesign the "Quick Links" section from the navbar.

@Alkaison  what you think about this
ww

**Comment by Alkaison** [comment]
Ok, will go for it.

**Pull request closed without merging**
