### PR TITLE
search function in blogs

### PR DESCRIPTION
**Pull request by Akanksha-202**
## Related Issue

Closes: #184 

## Description of Changes

- Added the search functionality in the blogs section.
- Blogs can be searched through the title and the author.
## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot
) | Updated screenshot
) |

[Video Preview]

https://github.com/ZeroOctave/resource-gallery/assets/100708686/db6b0643-1cab-4097-9592-799ba5be71ff

### CODE REVIEW

**Comment by Akanksha-202** [comment]
@bhartik021 please review and tell if any changes are req

**Comment by Akanksha-202** [comment]
@Astrodevil please check my PR

**Review by Alkaison — APPROVED** [review]
All good!

**Review by Alkaison — APPROVED** [review]
All good!

**Pull request merged**
