### PR TITLE
Share functionality added

### PR DESCRIPTION
**Pull request by Akanksha-202**
## Related Issue

Closes: #182 

## Description of Changes

-Added a share icon alongside the category of the blog
-Added the functionality of copying the link to the blog 
-Added an alert for confirmation

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
|      Updated       |  
[Video Preview]
https://www.loom.com/share/69d4b3e485194a848353c3e40b963ab6?sid=db23c2fb-0e8a-442d-8d9f-cc62bf3eec15

### CODE REVIEW

**Comment by Akanksha-202** [comment]
@Astrodevil Kindly review

**Comment by Alkaison** [comment]
Hi @Akanksha-202, can you please try to implement a pop-up message instead of Alert Message, because considering UI alert messages are not good.

**Comment by Akanksha-202** [comment]
https://github.com/ZeroOctave/resource-gallery/assets/100708686/97038a7e-af41-491f-b817-a444c02fe1ab

@Alkaison is this fine?

**Comment by Akanksha-202** [comment]
https://github.com/ZeroOctave/resource-gallery/assets/100708686/8c8cc6dd-fe1d-49ac-aa91-fbf3fba36845

Fixed that!

**Review by Alkaison — APPROVED** [review]
Great work 👏, soon it will be merged. Thank you @Akanksha-202 for your valuable contribution.

**Pull request merged**
