### PR TITLE
Add our team section

### PR DESCRIPTION
**Pull request by SubhamB2003**
## Related Issue
solves #211 

https://github.com/ZeroOctave/resource-gallery/assets/94003231/0726bfe5-7f02-4d36-8dd1-ba3364cc2073

Closes: #[issue number]

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Astrodevil** [comment]
Looking good, few suggestion:

Name the section (our Contributors) and remove mine and our mentor profiles from it as it is already in core team section. Also make core team section card round and contributors cards are fine juse decrease the size.

**Comment by SubhamB2003** [comment]
> Looking good, few suggestion:
> 
> Name the section (our Contributors) and remove mine and our mentor profiles from it as it is already in core team section. Also make core team section card round and contributors cards are fine juse decrease the size.
> 
> use colour (black or the existing gradient) on profile button

@Astrodevil Done. You can check now.

**Comment by Astrodevil** [comment]
Please share image or vid of latest change

**Comment by SubhamB2003** [comment]
> Please share image or vid of latest change

yes sure

https://github.com/ZeroOctave/resource-gallery/assets/94003231/a5efb149-7c3a-423a-9747-f7364a5d45cc

**Pull request merged**
