### PR TITLE
feat: javascript.info

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Related Issue

Closes: #259 

## Description of Changes
- **Added `javascript.info` Details in `javascript.astro` File for learning` JavaScript Beginners to More Advanced Level`**

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @Alkaison . Please review on this PR

**Review by Alkaison — APPROVED** [review]
All good! Try adding more resources for other topics too.

**Comment by NarendraKoya999** [comment]
> All good! Try adding more resources for other topics too.

Sure @Alkaison

**Comment by Astrodevil** [comment]
Solve conflict

**Comment by NarendraKoya999** [comment]
> Solve conflict

I resolved Merge Conflicts. Please Check @

**Review by Alkaison — APPROVED** [review]
All good 👍

**Pull request merged**
