### PR TITLE
blog added

### PR DESCRIPTION
**Pull request by anshulsoni4**
## Related Issue
added one more blog 

Closes: #229

## Description of Changes
added new blog

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

image

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anshulsoni4** [comment]
pls review

**Comment by anshulsoni4** [comment]
pls review

**Comment by Astrodevil** [comment]
Your directory is invalid, fix it

**Comment by anshulsoni4** [comment]
> Your directory is invalid, fix it

how can you explain ??

**Comment by Astrodevil** [comment]
You have made extra folder under blog look the path src/pages/blog/src/pages/blog/Low code and no-code tools.md

**Pull request merged**
