### PR TITLE
add new resources

### PR DESCRIPTION
**Pull request by Shreya111111**
## Related Issue

Closes: #169 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

Added new resources for cloud. Created a new section for cloud and added 6 resources under it including blogs, documentation and tutorials for aws, azure and google cloud.
Screenshot 2023-06-24 185434

Screenshot 2023-06-24 185457

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Shreya111111** [comment]
@bhartik021 @Astrodevil  @kartikkc plz review the issue #169 and PR #172  under gssoc'23

**Comment by Shreya111111** [comment]
@Astrodevil plz review the issue https://github.com/ZeroOctave/resource-gallery/issues/169 and PR https://github.com/ZeroOctave/resource-gallery/pull/172 under gssoc'23

**Comment by Shreya111111** [comment]
@Alkaison plz review the issue https://github.com/ZeroOctave/resource-gallery/issues/168 and PR https://github.com/ZeroOctave/resource-gallery/pull/170 under gssoc'23.

**Comment by Shreya111111** [comment]
@Alkaison plz review the issue https://github.com/ZeroOctave/resource-gallery/issues/169 and PR https://github.com/ZeroOctave/resource-gallery/pull/172 under gssoc'23

**Review by Alkaison — APPROVED** [review]
Code is perfect.

**Comment by Alkaison** [comment]
Next time make sure you are more descriptive while providing the PR, Thanks @Shreya111111 Great work!

**Comment by Shreya111111** [comment]
@Astrodevil  plz review the PR

**Comment by Shreya111111** [comment]
@Astrodevil it has been too long and almost more than a week now. kindly review the PR

**Comment by Shreya111111** [comment]
@Astrodevil I have updated the info and screenshots provided

**Comment by Shreya111111** [comment]
@Astrodevil kindly review the pr

**Comment by Shreya111111** [comment]
@Astrodevil kindly review the pr

**Comment by Shreya111111** [comment]
@Astrodevil kindly merge this too

**Pull request merged**
