### PR TITLE
Added in resources - Blog and website

### PR DESCRIPTION
**Pull request by Abhinavcode13**
## Related Issue

Closes: #38 

## Description of Changes
Added two new resource blog and website for react.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Please check now the PR @Astrodevil

**Comment by Abhinavcode13** [comment]
The the files 2 new resources in the framework @Astrodevil

**Comment by bhartik021** [comment]
@Abhinavcode13  Please provide screenshot

**Comment by Abhinavcode13** [comment]
image

**Comment by Abhinavcode13** [comment]
check now @bhartik021 @Astrodevil

**Comment by Abhinavcode13** [comment]
Just check now I updated the files

**Review by bhartik021 — APPROVED** [review]

**Pull request merged**
