### PR TITLE
Added New Article on "How Does JavaScript Work Behind the Scenes?"

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue

Closes: #[issue number]

## Description of Changes
📝 Added an informative article to the JavaScript resources section in the resource gallery website.

 
**Article Title:** "How Does JavaScript Work Behind the Scenes? JS Engine and Runtime Explained"

**Description:**
The article provides an in-depth exploration of how JavaScript works behind the scenes, shedding light on the JS Engine and Runtime. It explains the core concepts, the role of the JS Engine in executing code, and the runtime environment where JavaScript code runs. The article aims to demystify the inner workings of JavaScript, making it an excellent addition to the resource gallery for learners and developers.

**Article Content:**
[Link to the Article](https://medium.com/@nishitbaria/how-does-javascript-work-behind-the-scenes-7c321b113bcc)

I'm excited to contribute this valuable resource to the community and welcome any feedback or suggestions for improvements. Let me know if there's anything else I can do to enhance this contribution.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@Astrodevil ,please review and merge my pull request

**Review by Alkaison — APPROVED** [review]
All good!

**Comment by Nishitbaria** [comment]
@Astrodevil ,please review and merge my pull request

**Comment by Nishitbaria** [comment]
@Astrodevil ,please review and merge

**Pull request merged**
