### PR TITLE
Mern stack blog added

### PR DESCRIPTION
**Pull request by Abhinavcode13**
## Related Issue

Closes: #96 

## Description of Changes

Added MERN stack blog.

Unlock the full potential of the MERN stack with these expert-backed best practices and tools

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
@bhartik021 please check this i have provided ss also.

**Comment by Abhinavcode13** [comment]
@bhartik021 any update?

**Comment by Abhinavcode13** [comment]
@bhartik021 @Astrodevil ??

**Comment by Astrodevil** [comment]
Blog is  too small but atleast please raise new PR, some errors while merging.

**Pull request closed without merging**
