### PR TITLE
Added ScrollToTop button

### PR DESCRIPTION
**Pull request by saikiranreddy201**
## Related Issue

Closes: #132 

## Description of Changes
- I have added the respective component and its functionality in the codebase
- It matches the UI and I have tested it.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

image

### CODE REVIEW

**Comment by Alkaison** [comment]
Revert the changes in `pnpm.yaml` as it was not suppose to make any changes into it.

**Comment by saikiranreddy201** [comment]
Should I delete it and push it? @Alkaison

**Comment by Alkaison** [comment]
copy the current content from the repo for `pnpm.yaml` and paste it into the file and push.

Copy from here: https://github.com/ZeroOctave/resource-gallery/blob/main/pnpm-lock.yaml
Paste the whole content as it is.

**Review by Alkaison — APPROVED** [review]
All good! 👍

**Comment by Alkaison** [comment]
Can you share a video of the working of it?

**Comment by saikiranreddy201** [comment]
Here is the working video

https://github.com/ZeroOctave/resource-gallery/assets/98690105/a8eb2c4b-5252-4964-a0bd-ed179b2e1e15

**Pull request merged**
